try

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,4 +1,15 @@
 #!/usr/bin/env bash
-# Gracefully reloads Gunicorn.
+# Get the PID of the Gunicorn master process
+master_pid=$(ps aux | grep '[g]unicorn' | awk '{print $2}')
 
-ps aux | grep gunicorn | awk '{ print $2 }' | xargs kill -HUP
+# Check if Gunicorn master process is running
+if [ -z "$master_pid" ]; then
+    echo "Gunicorn master process not found. Make sure Gunicorn is running."
+    exit 1
+fi
+
+# Gracefully restart Gunicorn master process
+kill -s HUP "$master_pid"
+
+echo "Gunicorn master process has been gracefully restarted."
+
